In [21]:
import pandas as pd
import numpy
import requests
import json
import matplotlib.pyplot as plt
import os
from pathlib import Path
import sys

In [22]:
wka = pd.read_excel("../data/raw/Zeitreihen_WKA_2025_2026.xlsx")
weather = pd.read_excel("../data/raw/Zeitreihen_Wetterprognosen_2025_2026.xlsx")

In [23]:
wka.head(10)

,Größe,Unnamed: 1,kW el,kW el.1
0,Richtung,NaN,Einsp,Einsp
1,Zeitraster Min,NaN,15,15
2,Zeitverschiebung UTC,NaN,UTC+1,UTC+1
3,Lokale Zeit,NaN,Nein,Nein
4,Datum_von,Datum_bis,Unterpreilipp_Rudolstadt,Burgau_Jena
5,2025-01-01 00:00:00,01.01.2025 00:15:00,812,851.4
6,01.01.2025 00:15:00,01.01.2025 00:30:00,810,851.8
7,01.01.2025 00:30:00,01.01.2025 00:45:00,808,849.4
8,01.01.2025 00:45:00,01.01.2025 01:00:00,814,844.6
9,01.01.2025 01:00:00,01.01.2025 01:15:00,810,845

In [35]:
weather.head(10)

,Größe,Unnamed: 1,Globalstrahlung W/qm,Temperatur C,Windgeschwindigkeit m/s,Windrichtung
0,Zustand,NaN,Prognose,Prognose,Prognose,Prognose
1,Zeitraster Min,NaN,15,15,15,15
2,Zeitverschiebung UTC,NaN,UTC+1,UTC+1,UTC+1,UTC+1
3,Lokale Zeit,NaN,Nein,Nein,Nein,Nein
4,Datum_von,Datum_bis,Wert,Wert,Wert,Wert
5,01.01.2025 00:00:00,01.01.2025 00:15:00,0,0.7,8,222
6,01.01.2025 00:15:00,01.01.2025 00:30:00,0,0.7,8,222
7,01.01.2025 00:30:00,01.01.2025 00:45:00,0,0.7,8,222
8,01.01.2025 00:45:00,01.01.2025 01:00:00,0,0.7,8,222
9,01.01.2025 01:00:00,01.01.2025 01:15:00,0,-0.2,7,226

In [24]:

url = "https://kshww2.thueringen.de/FROST-Server/v1.1/Things"

response = requests.get(url, timeout=30)
data = response.json()

result = {
    thing["name"]: {
        "description": thing.get("description"),
        "properties": thing.get("properties", {})
    }
    for thing in data["value"]
}

In [25]:
result

{'4834900280': {'description': 'groundwater station (auto-importer)',
  'properties': {'creation_date': '2024-08-13T17:01:25.803000',
   'station_id': '4834900280',
   'type': 'AUTO_IMPORT_SENF'}},
 'Grundwasserstation@5031210655': {'description': 'groundwater station (auto-importer)',
  'properties': {'creation_date': '2024-08-13T17:02:04.725852',
   'station_id': '5031210655',
   'type': 'AUTO_IMPORT_SENF'}},
 'Grundwasserstation@5032210675': {'description': '',
  'properties': {'creation_date': '2024-11-19T13:21:27.821157',
   'station_id': '5032210675',
   'type': 'AUTO_IMPORT_SENF'}},
 'Bodenfeuchte_Messstation@121588': {'description': '',
  'properties': {'creation_date': '2024-11-19T13:48:31.251772',
   'station_id': '121588',
   'type': 'AUTO_IMPORT_SENF'}},
 'Bodenfeuchte_Messstation@121589': {'description': '',
  'properties': {'creation_date': '2024-11-19T16:27:15.585112',
   'station_id': '121589',
   'type': 'AUTO_IMPORT_SENF'}},
 'Bodenfeuchte_Messstation@121590': {'description': '',
  'properties': {'creation_date': '2024-11-19T18:28:24.776749',
   'station_id': '121590',
   'type': 'AUTO_IMPORT_SENF'}},
 'Bodenfeuchte_Messstation@121591': {'description': '',
  'properties': {'creation_date': '2024-11-19T21:20:19.525977',
   'station_id': '121591',
   'type': 'AUTO_IMPORT_SENF'}},
 'Bodenfeuchte_Messstation@121593': {'description': '',
  'properties': {'creation_date': '2024-11-20T00:57:35.793343',
   'station_id': '121593',
   'type': 'AUTO_IMPORT_SENF'}},
 'Rothenstein': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-27T17:10:38.135601',
   'gewaesser': 'Saale',
   'station_id': 570280,
   'type': 'TH_PEGEL'}},
 'Kaltennordheim': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-27T17:15:08.850041',
   'gewaesser': 'Felda',
   'station_id': 426050,
   'type': 'TH_PEGEL'}},
 'Eisenach-Petersberg': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-27T17:15:37.732776',
   'gewaesser': 'Hörsel',
   'station_id': 429010,
   'type': 'TH_PEGEL'}},
 'Teutleben': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-27T17:16:05.881364',
   'gewaesser': 'Hörsel',
   'station_id': 429050,
   'type': 'TH_PEGEL'}},
 'Sondra 1': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-27T17:16:33.190179',
   'gewaesser': 'Emse',
   'station_id': 429450,
   'type': 'TH_PEGEL'}},
 'Eisenach-Nessemühle': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-27T17:17:01.538351',
   'gewaesser': 'Nesse',
   'station_id': 429600,
   'type': 'TH_PEGEL'}},
 'Wangenheim': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-27T17:17:28.508841',
   'gewaesser': 'Nesse',
   'station_id': 429650,
   'type': 'TH_PEGEL'}},
 'Schönau v.d. Walde 2 (alt)': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-27T17:17:56.647353',
   'gewaesser': 'Leina-Kanal',
   'station_id': 429700,
   'type': 'TH_PEGEL'}},
 'Schönau v.d. Walde 1': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-27T17:17:57.576528',
   'gewaesser': 'Leina',
   'station_id': 429740,
   'type': 'TH_PEGEL'}},
 'Arenshausen': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-27T17:18:24.161999',
   'gewaesser': 'Leine',
   'station_id': 447000,
   'type': 'TH_PEGEL'}},
 'Geisleden': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-27T17:18:51.605793',
   'gewaesser': 'Geislede',
   'station_id': 447110,
   'type': 'TH_PEGEL'}},
 'Blankenstein-Rosenthal': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-27T17:19:18.338674',
   'gewaesser': 'Saale',
   'station_id': 570210,
   'type': 'TH_PEGEL'}},
 'Saalfeld-Remschütz': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T08:50:49.500231',
   'gewaesser': 'Saale',
   'station_id': 570260,
   'type': 'TH_PEGEL'}},
 'Harra-Lemnitzhammer': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T08:51:25.329019',
   'gewaesser': 'Lemnitz',
   'station_id': 571500,
   'type': 'TH_PEGEL'}},
 'Möschlitz': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T08:51:55.007144',
   'gewaesser': 'Wisenta',
   'station_id': 571700,
   'type': 'TH_PEGEL'}},
 'Leutenberg (alt)': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T08:52:30.008265',
   'gewaesser': 'Sormitz',
   'station_id': 572060,
   'type': 'TH_PEGEL'}},
 'Katzhütte-Schwarza': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T08:53:01.069344',
   'gewaesser': 'Schwarza',
   'station_id': 572110,
   'type': 'TH_PEGEL'}},
 'Zöllnitz': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T08:54:09.662603',
   'gewaesser': 'Roda',
   'station_id': 572600,
   'type': 'TH_PEGEL'}},
 'Mellingen': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T08:54:36.746047',
   'gewaesser': 'Ilm',
   'station_id': 572910,
   'type': 'TH_PEGEL'}},
 'HRB Straußfurt (AP)': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T08:55:29.067187',
   'gewaesser': 'Unstrut',
   'station_id': 573100,
   'type': 'TH_PEGEL'}},
 'Artern': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T08:55:57.781781',
   'gewaesser': 'Unstrut',
   'station_id': 573120,
   'type': 'TH_PEGEL'}},
 'Körner': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T08:56:23.612599',
   'gewaesser': 'Notter',
   'station_id': 574080,
   'type': 'TH_PEGEL'}},
 'Werningshausen 2': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T08:57:53.477040',
   'gewaesser': 'Neue Gramme',
   'station_id': 574930,
   'type': 'TH_PEGEL'}},
 'Erfurt 2 (alt)': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T08:58:19.233287',
   'gewaesser': 'Schmale Gera',
   'station_id': 574940,
   'type': 'TH_PEGEL'}},
 'Frohndorf 1': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T08:58:23.943656',
   'gewaesser': 'Lossa',
   'station_id': 575020,
   'type': 'TH_PEGEL'}},
 'Vogelsberg (alt)': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T08:58:51.867220',
   'gewaesser': 'Scherkonde',
   'station_id': 575031,
   'type': 'TH_PEGEL'}},
 'Frohndorf 2': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T08:58:54.523141',
   'gewaesser': 'Scherkonde',
   'station_id': 575050,
   'type': 'TH_PEGEL'}},
 'Bellstedt (alt)': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T08:59:25.276821',
   'gewaesser': 'Helbe',
   'station_id': 575079,
   'type': 'TH_PEGEL'}},
 'Thalebra (alt)': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T08:59:26.597772',
   'gewaesser': 'Sumpfbach',
   'station_id': 575080,
   'type': 'TH_PEGEL'}},
 'Westgreußen 1 (alt)': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T08:59:29.827411',
   'gewaesser': 'Schwarzburgsche Helbe',
   'station_id': 575170,
   'type': 'TH_PEGEL'}},
 'Greußen (alt)': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T08:59:31.095937',
   'gewaesser': 'Steingraben',
   'station_id': 575180,
   'type': 'TH_PEGEL'}},
 'Bernterode': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T08:59:33.548553',
   'gewaesser': 'Wipper',
   'station_id': 575190,
   'type': 'TH_PEGEL'}},
 'Großfurra (alt)': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T08:59:54.008896',
   'gewaesser': 'Wipper',
   'station_id': 575220,
   'type': 'TH_PEGEL'}},
 'Sundhausen': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T08:59:57.526772',
   'gewaesser': 'Helme',
   'station_id': 575400,
   'type': 'TH_PEGEL'}},
 'Ellrich': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:00:25.940925',
   'gewaesser': 'Zorge',
   'station_id': 575620,
   'type': 'TH_PEGEL'}},
 'Stempeda 2 (AP)': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:00:51.127260',
   'gewaesser': 'Krebsbach',
   'station_id': 575730,
   'type': 'TH_PEGEL'}},
 'Gera-Langenberg': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:01:25.039157',
   'gewaesser': 'Weiße Elster',
   'station_id': 576520,
   'type': 'TH_PEGEL'}},
 'Ringleben 1 (alt)': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:02:25.026617',
   'gewaesser': 'Gera',
   'station_id': 574280,
   'type': 'TH_PEGEL'}},
 'Gehlberg': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:02:26.723519',
   'gewaesser': 'Wilde Gera',
   'station_id': 574300,
   'type': 'TH_PEGEL'}},
 'Lütsche 2 (alt)': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:02:53.293783',
   'gewaesser': 'Oberster Wiesengrund',
   'station_id': 574360,
   'type': 'TH_PEGEL'}},
 'Steinach': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:02:54.344927',
   'gewaesser': 'Steinach',
   'station_id': 252401,
   'type': 'TH_PEGEL'}},
 'Sonneberg (alt)': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:25:48.839908',
   'gewaesser': 'Röden',
   'station_id': 252530,
   'type': 'TH_PEGEL'}},
 'Hüttengrund': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:03:23.299351',
   'gewaesser': 'Engnitz',
   'station_id': 252460,
   'type': 'TH_PEGEL'}},
 'Döhlau': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:03:49.682504',
   'gewaesser': 'Effelder',
   'station_id': 252520,
   'type': 'TH_PEGEL'}},
 'Lindenau (alt)': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:04:19.025169',
   'gewaesser': 'Kreck',
   'station_id': 253530,
   'type': 'TH_PEGEL'}},
 'Eisfeld-Bahnbrücke': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:04:28.352247',
   'gewaesser': 'Werra',
   'station_id': 420001,
   'type': 'TH_PEGEL'}},
 'Ebenhards (ZP)': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:04:54.517625',
   'gewaesser': 'Werra',
   'station_id': 420011,
   'type': 'TH_PEGEL'}},
 'Plaue': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:05:21.182646',
   'gewaesser': 'Zahme Gera',
   'station_id': 574411,
   'type': 'TH_PEGEL'}},
 'Niederwillingen': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:06:13.435699',
   'gewaesser': 'Wipfra',
   'station_id': 574540,
   'type': 'TH_PEGEL'}},
 'Georgenthal 1': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:06:43.064864',
   'gewaesser': 'Apfelstädt',
   'station_id': 574620,
   'type': 'TH_PEGEL'}},
 'Tambach-Dietharz 4 (alt)': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:09:45.431071',
   'gewaesser': 'Schmalwasser',
   'station_id': 574710,
   'type': 'TH_PEGEL'}},
 'Luisenthal 2 (ZP TS Ohra) (alt)': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:10:45.826649',
   'gewaesser': 'Silbergraben',
   'station_id': 574780,
   'type': 'TH_PEGEL'}},
 'Ringleben 2': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:11:59.148088',
   'gewaesser': 'Mahlgera',
   'station_id': 574840,
   'type': 'TH_PEGEL'}},
 'Bruchstedt (alt)': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:12:25.881727',
   'gewaesser': 'Fernebach',
   'station_id': 574850,
   'type': 'TH_PEGEL'}},
 'Urleben': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:12:28.346772',
   'gewaesser': 'Singerbach',
   'station_id': 574880,
   'type': 'TH_PEGEL'}},
 'Werningshausen 1': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:12:30.262230',
   'gewaesser': 'Alte Gramme',
   'station_id': 574900,
   'type': 'TH_PEGEL'}},
 'Grimmelshausen (alt)': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:12:56.817920',
   'gewaesser': 'Werra',
   'station_id': 420010,
   'type': 'TH_PEGEL'}},
 'Lütsche 3 (alt)': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:12:57.855162',
   'gewaesser': 'Langer Grund',
   'station_id': 574370,
   'type': 'TH_PEGEL'}},
 'Gräfenroda': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:13:03.437885',
   'gewaesser': 'Wilde Gera',
   'station_id': 574420,
   'type': 'TH_PEGEL'}},
 'Eischleben': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:13:29.459218',
   'gewaesser': 'Wipfra',
   'station_id': 574500,
   'type': 'TH_PEGEL'}},
 'Sondershausen': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:14:25.510078',
   'gewaesser': 'Wipper',
   'station_id': 575230,
   'type': 'TH_PEGEL'}},
 'Hachelbich': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:14:51.895432',
   'gewaesser': 'Wipper',
   'station_id': 575240,
   'type': 'TH_PEGEL'}},
 'Kleinbodungen (alt)': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:15:20.001614',
   'gewaesser': 'Bode',
   'station_id': 575260,
   'type': 'TH_PEGEL'}},
 'Ilfeld': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:15:27.612652',
   'gewaesser': 'Bere',
   'station_id': 575660,
   'type': 'TH_PEGEL'}},
 'Stempeda 1  (ZP) (alt)': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:16:04.378875',
   'gewaesser': 'Krebsbach',
   'station_id': 575800,
   'type': 'TH_PEGEL'}},
 'TS Krebsbach (ZP) (alt)': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:16:11.719152',
   'gewaesser': 'Krebsbach',
   'station_id': 577240,
   'type': 'TH_PEGEL'}},
 'Weida': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:16:47.679198',
   'gewaesser': 'Weida',
   'station_id': 577320,
   'type': 'TH_PEGEL'}},
 'Eisenhammer (AP)': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:17:49.032304',
   'gewaesser': 'Auma',
   'station_id': 577360,
   'type': 'TH_PEGEL'}},
 'Gößnitz': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:18:17.601163',
   'gewaesser': 'Pleiße',
   'station_id': 577510,
   'type': 'TH_PEGEL'}},
 'Mupperg': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:24:26.352759',
   'gewaesser': 'Steinach',
   'station_id': 252450,
   'type': 'TH_PEGEL'}},
 'Almerswind-Itz': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:24:53.425314',
   'gewaesser': 'Itz',
   'station_id': 252500,
   'type': 'TH_PEGEL'}},
 'Almerswind-Grümpen': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:25:19.362340',
   'gewaesser': 'Grümpen',
   'station_id': 252510,
   'type': 'TH_PEGEL'}},
 'Milz': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:25:58.388781',
   'gewaesser': 'Spring',
   'station_id': 256120,
   'type': 'TH_PEGEL'}},
 'Westgreußen 2 (alt)': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:26:26.838711',
   'gewaesser': 'Sächsische Helbe',
   'station_id': 575160,
   'type': 'TH_PEGEL'}},
 'Meiningen': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:27:26.362360',
   'gewaesser': 'Werra',
   'station_id': 420020,
   'type': 'TH_PEGEL'}},
 'Vacha': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:27:56.437534',
   'gewaesser': 'Werra',
   'station_id': 420120,
   'type': 'TH_PEGEL'}},
 'Gerstungen': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:28:23.803838',
   'gewaesser': 'Werra',
   'station_id': 420170,
   'type': 'TH_PEGEL'}},
 'Frankenroda': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:28:54.688352',
   'gewaesser': 'Werra',
   'station_id': 420190,
   'type': 'TH_PEGEL'}},
 'Hinternah': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:32:22.529255',
   'gewaesser': 'Nahe',
   'station_id': 421600,
   'type': 'TH_PEGEL'}},
 'Ellingshausen': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:33:48.287040',
   'gewaesser': 'Hasel',
   'station_id': 422000,
   'type': 'TH_PEGEL'}},
 'Schwarza': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:34:18.233984',
   'gewaesser': 'Schwarza',
   'station_id': 422300,
   'type': 'TH_PEGEL'}},
 'Oberschönau': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:34:46.802878',
   'gewaesser': 'Haselbach',
   'station_id': 422450,
   'type': 'TH_PEGEL'}},
 'Mittelschmalkalden': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:35:17.120635',
   'gewaesser': 'Schmalkalde',
   'station_id': 424000,
   'type': 'TH_PEGEL'}},
 'Trusetal-Wahles': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:35:45.766734',
   'gewaesser': 'Truse',
   'station_id': 425121,
   'type': 'TH_PEGEL'}},
 'Breitungen': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:36:18.962051',
   'gewaesser': 'Werra',
   'station_id': 420070,
   'type': 'TH_PEGEL'}},
 'Rappelsdorf': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:37:17.921655',
   'gewaesser': 'Schleuse',
   'station_id': 421510,
   'type': 'TH_PEGEL'}},
 'Schleusingen': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:38:16.892036',
   'gewaesser': 'Nahe',
   'station_id': 421620,
   'type': 'TH_PEGEL'}},
 'Suhl': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:38:48.917770',
   'gewaesser': 'Lauter',
   'station_id': 422201,
   'type': 'TH_PEGEL'}},
 'Obermaßfeld': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:39:17.911587',
   'gewaesser': 'Parthe',
   'station_id': 423050,
   'type': 'TH_PEGEL'}},
 'Liebschütz': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:41:09.075396',
   'gewaesser': 'Otterbach',
   'station_id': 571900,
   'type': 'TH_PEGEL'}},
 'Blankenburg-Weidmannsheil (alt)': {'description': 'Abflusspegel',
  'properties': {'creation_date': '2024-11-28T09:42:14.413801',
   'gewaesser': 'Schwarza',
   'station_id': 572120,
   'type': 'TH_PEGEL'}}}

In [26]:
locations = list(result.keys())

In [27]:
# hack
project_root = Path.cwd().parent  
sys.path.append(str(project_root))

In [28]:
#fetching the data from the water locations
from src.data.fetch_data import fetch_data_good

# default Q becase m³ / s is more useful than cm
default_param = "Q"
day_data = "1D"
min_data = "15min"
start_date = "2025-01-01"
end_date = "2026-01-01"

In [29]:
missing_stations = 0
# takes a while, uncomment for fetch
for station in locations:
    try:
        fetch_data_good(station, default_param, min_data, start_date, end_date, "../data/raw/water_data")
    except:
        missing_stations += 1

Station=4834900280  Parameter=Q  Freq=15min  2025-01-01T00:00:00Z → 2026-01-01T00:00:00Z

Error fetching No datastream for parameter='Q', freq='15min' on Thing 113. Run explore_api.py → list_datastreams(113) to see what is available.
Station=Grundwasserstation@5031210655  Parameter=Q  Freq=15min  2025-01-01T00:00:00Z → 2026-01-01T00:00:00Z

Error fetching No datastream for parameter='Q', freq='15min' on Thing 124. Run explore_api.py → list_datastreams(124) to see what is available.
Station=Grundwasserstation@5032210675  Parameter=Q  Freq=15min  2025-01-01T00:00:00Z → 2026-01-01T00:00:00Z

Error fetching No datastream for parameter='Q', freq='15min' on Thing 176. Run explore_api.py → list_datastreams(176) to see what is available.
Station=Bodenfeuchte_Messstation@121588  Parameter=Q  Freq=15min  2025-01-01T00:00:00Z → 2026-01-01T00:00:00Z

Error fetching No datastream for parameter='Q', freq='15min' on Thing 178. Run explore_api.py → list_datastreams(178) to see what is available.
Station=Bodenfeuchte_Messstation@121589  Parameter=Q  Freq=15min  2025-01-01T00:00:00Z → 2026-01-01T00:00:00Z

Error fetching No datastream for parameter='Q', freq='15min' on Thing 179. Run explore_api.py → list_datastreams(179) to see what is available.
Station=Bodenfeuchte_Messstation@121590  Parameter=Q  Freq=15min  2025-01-01T00:00:00Z → 2026-01-01T00:00:00Z

Error fetching No datastream for parameter='Q', freq='15min' on Thing 180. Run explore_api.py → list_datastreams(180) to see what is available.
Station=Bodenfeuchte_Messstation@121591  Parameter=Q  Freq=15min  2025-01-01T00:00:00Z → 2026-01-01T00:00:00Z

Error fetching No datastream for parameter='Q', freq='15min' on Thing 181. Run explore_api.py → list_datastreams(181) to see what is available.
Station=Bodenfeuchte_Messstation@121593  Parameter=Q  Freq=15min  2025-01-01T00:00:00Z → 2026-01-01T00:00:00Z

Error fetching No datastream for parameter='Q', freq='15min' on Thing 182. Run explore_api.py → list_datastreams(182) to see what is available.
Station=Rothenstein  Parameter=Q  Freq=15min  2025-01-01T00:00:00Z → 2026-01-01T00:00:00Z

Datastream: [7510] Q@Rothenstein/Saale (m³/s)  available: 2025-06-12T10:00:00Z/2026-06-13T09:45:00Z

  fetched 1000 / 19449
  fetched 2000 / 19449
  fetched 3000 / 19449
  fetched 4000 / 19449
  fetched 5000 / 19449
  fetched 6000 / 19449
  fetched 7000 / 19449
  fetched 8000 / 19449
  fetched 9000 / 19449
  fetched 10000 / 19449
  fetched 11000 / 19449
  fetched 12000 / 19449
  fetched 13000 / 19449
  fetched 14000 / 19449
  fetched 15000 / 19449
  fetched 16000 / 19449
  fetched 17000 / 19449
  fetched 18000 / 19449
  fetched 19000 / 19449
  fetched 19449 / 19449

Saved 19449 rows to '../data/raw/water_data/Q_Rothenstein_15min.csv'
Station=Kaltennordheim  Parameter=Q  Freq=15min  2025-01-01T00:00:00Z → 2026-01-01T00:00:00Z

Datastream: [7543] Q@Kaltennordheim/Felda (m³/s)  available: 2025-06-12T10:00:00Z/2026-06-13T08:00:00Z

  fetched 1000 / 19449
  fetched 2000 / 19449
  fetched 3000 / 19449
  fetched 4000 / 19449
  fetched 5000 / 19449
  fetched 6000 / 19449
  fetched 7000 / 19449
  fetched 8000 / 19449
  fetched 9000 / 19449
  fetched 10000 / 19449
  fetched 11000 / 19449
  fetched 12000 / 19449
  fetched 13000 / 19449
  fetched 14000 / 19449
  fetched 15000 / 19449
  fetched 16000 / 19449
  fetched 17000 / 19449
  fetched 18000 / 19449
  fetched 19000 / 19449
  fetched 19449 / 19449

Saved 19449 rows to '../data/raw/water_data/Q_Kaltennordheim_15min.csv'
Station=Eisenach-Petersberg  Parameter=Q  Freq=15min  2025-01-01T00:00:00Z → 2026-01-01T00:00:00Z

Datastream: [7467] Q@Eisenach-Petersberg/Hörsel (m³/s)  available: 2025-06-12T10:00:00Z/2026-06-13T09:45:00Z

  fetched 1000 / 19449
  fetched 2000 / 19449
  fetched 3000 / 19449
  fetched 4000 / 19449
  fetched 5000 / 19449
  fetched 6000 / 19449
  fetched 7000 / 19449
  fetched 8000 / 19449
  fetched 9000 / 19449
  fetched 10000 / 19449
  fetched 11000 / 19449
  fetched 12000 / 19449
  fetched 13000 / 19449
  fetched 14000 / 19449
  fetched 15000 / 19449
  fetched 16000 / 19449
  fetched 17000 / 19449
  fetched 18000 / 19449
  fetched 19000 / 19449
  fetched 19449 / 19449

Saved 19449 rows to '../data/raw/water_data/Q_Eisenach-Petersberg_15min.csv'
Station=Teutleben  Parameter=Q  Freq=15min  2025-01-01T00:00:00Z → 2026-01-01T00:00:00Z

Datastream: [7505] Q@Teutleben/Hörsel (m³/s)  available: 2025-06-12T10:00:00Z/2026-06-13T09:45:00Z

  fetched 1000 / 19449
  fetched 2000 / 19449
  fetched 3000 / 19449
  fetched 4000 / 19449
  fetched 5000 / 19449
  fetched 6000 / 19449
  fetched 7000 / 19449
  fetched 8000 / 19449
  fetched 9000 / 19449
  fetched 10000 / 19449
  fetched 11000 / 19449
  fetched 12000 / 19449
  fetched 13000 / 19449
  fetched 14000 / 19449
  fetched 15000 / 19449
  fetched 16000 / 19449
  fetched 17000 / 19449
  fetched 18000 / 19449
  fetched 19000 / 19449
  fetched 19449 / 19449

Saved 19449 rows to '../data/raw/water_data/Q_Teutleben_15min.csv'
Station=Sondra 1  Parameter=Q  Freq=15min  2025-01-01T00:00:00Z → 2026-01-01T00:00:00Z

Datastream: [7441] Q@Sondra 1/Emse (m³/s)  available: 2025-06-12T10:00:00Z/2026-06-13T09:30:00Z

  fetched 1000 / 19549
  fetched 2000 / 19549
  fetched 3000 / 19549
  fetched 4000 / 19549
  fetched 5000 / 19549
  fetched 6000 / 19549
  fetched 7000 / 19549
  fetched 8000 / 19549
  fetched 9000 / 19549
  fetched 10000 / 19549
  fetched 11000 / 19549
  fetched 12000 / 19549
  fetched 13000 / 19549
  fetched 14000 / 19549
  fetched 15000 / 19549
  fetched 16000 / 19549
  fetched 17000 / 19549
  fetched 18000 / 19549
  fetched 19000 / 19549
  fetched 19549 / 19549

Saved 19549 rows to '../data/raw/water_data/Q_Sondra_1_15min.csv'
Station=Eisenach-Nessemühle  Parameter=Q  Freq=15min  2025-01-01T00:00:00Z → 2026-01-01T00:00:00Z

Datastream: [7454] Q@Eisenach-Nessemühle/Nesse (m³/s)  available: 2025-06-12T10:00:00Z/2026-06-13T09:45:00Z

  fetched 1000 / 19449
  fetched 2000 / 19449
  fetched 3000 / 19449
  fetched 4000 / 19449
  fetched 5000 / 19449
  fetched 6000 / 19449
  fetched 7000 / 19449
  fetched 8000 / 19449
  fetched 9000 / 19449
  fetched 10000 / 19449
  fetched 11000 / 19449
  fetched 12000 / 19449
  fetched 13000 / 19449
  fetched 14000 / 19449
  fetched 15000 / 19449
  fetched 16000 / 19449
  fetched 17000 / 19449
  fetched 18000 / 19449
  fetched 19000 / 19449
  fetched 19449 / 19449

Saved 19449 rows to '../data/raw/water_data/Q_Eisenach-Nessemühle_15min.csv'
Station=Wangenheim  Parameter=Q  Freq=15min  2025-01-01T00:00:00Z → 2026-01-01T00:00:00Z

Datastream: [7473] Q@Wangenheim/Nesse (m³/s)  available: 2025-06-12T10:00:00Z/2026-06-13T09:30:00Z

  fetched 1000 / 19449
  fetched 2000 / 19449
  fetched 3000 / 19449
  fetched 4000 / 19449
  fetched 5000 / 19449
  fetched 6000 / 19449
  fetched 7000 / 19449
  fetched 8000 / 19449
  fetched 9000 / 19449
  fetched 10000 / 19449
  fetched 11000 / 19449
  fetched 12000 / 19449
  fetched 13000 / 19449
  fetched 14000 / 19449
  fetched 15000 / 19449
  fetched 16000 / 19449
  fetched 17000 / 19449
  fetched 18000 / 19449
  fetched 19000 / 19449
  fetched 19449 / 19449

Saved 19449 rows to '../data/raw/water_data/Q_Wangenheim_15min.csv'
Station=Schönau v.d. Walde 2 (alt)  Parameter=Q  Freq=15min  2025-01-01T00:00:00Z → 2026-01-01T00:00:00Z

Error fetching No datastream for parameter='Q', freq='15min' on Thing 197. Run explore_api.py → list_datastreams(197) to see what is available.
Station=Schönau v.d. Walde 1  Parameter=Q  Freq=15min  2025-01-01T00:00:00Z → 2026-01-01T00:00:00Z

Datastream: [7559] Q@Schönau v.d. Walde 1/Leina (m³/s)  available: 2025-06-12T10:00:00Z/2026-06-13T09:30:00Z

  fetched 1000 / 19449
  fetched 2000 / 19449
  fetched 3000 / 19449
  fetched 4000 / 19449
  fetched 5000 / 19449
  fetched 6000 / 19449
  fetched 7000 / 19449
  fetched 8000 / 19449
  fetched 9000 / 19449
  fetched 10000 / 19449
  fetched 11000 / 19449
  fetched 12000 / 19449
  fetched 13000 / 19449
  fetched 14000 / 19449
  fetched 15000 / 19449
  fetched 16000 / 19449
  fetched 17000 / 19449
  fetched 18000 / 19449
  fetched 19000 / 19449
  fetched 19449 / 19449

Saved 19449 rows to '../data/raw/water_data/Q_Schönau_v.d._Walde_1_15min.csv'
Station=Arenshausen  Parameter=Q  Freq=15min  2025-01-01T00:00:00Z → 2026-01-01T00:00:00Z

Datastream: [7470] Q@Arenshausen/Leine (m³/s)  available: 2025-06-12T10:00:00Z/2026-06-13T09:45:00Z

  fetched 1000 / 19449
  fetched 2000 / 19449
  fetched 3000 / 19449
  fetched 4000 / 19449
  fetched 5000 / 19449
  fetched 6000 / 19449
  fetched 7000 / 19449
  fetched 8000 / 19449
  fetched 9000 / 19449
  fetched 10000 / 19449
  fetched 11000 / 19449
  fetched 12000 / 19449
  fetched 13000 / 19449
  fetched 14000 / 19449
  fetched 15000 / 19449
  fetched 16000 / 19449
  fetched 17000 / 19449
  fetched 18000 / 19449
  fetched 19000 / 19449
  fetched 19449 / 19449

Saved 19449 rows to '../data/raw/water_data/Q_Arenshausen_15min.csv'
Station=Geisleden  Parameter=Q  Freq=15min  2025-01-01T00:00:00Z → 2026-01-01T00:00:00Z

Datastream: [7475] Q@Geisleden/Geislede (m³/s)  available: 2025-06-12T10:00:00Z/2026-06-12T00:00:00Z

  fetched 1000 / 19450
  fetched 2000 / 19450
  fetched 3000 / 19450
  fetched 4000 / 19450
  fetched 5000 / 19450
  fetched 6000 / 19450
  fetched 7000 / 19450
  fetched 8000 / 19450
  fetched 9000 / 19450
  fetched 10000 / 19450
  fetched 11000 / 19450
  fetched 12000 / 19450
  fetched 13000 / 19450
  fetched 14000 / 19450
  fetched 15000 / 19450
  fetched 16000 / 19450
  fetched 17000 / 19450
  fetched 18000 / 19450
  fetched 19000 / 19450
  fetched 19450 / 19450

Saved 19450 rows to '../data/raw/water_data/Q_Geisleden_15min.csv'
Station=Blankenstein-Rosenthal  Parameter=Q  Freq=15min  2025-01-01T00:00:00Z → 2026-01-01T00:00:00Z

Datastream: [7522] Q@Blankenstein-Rosenthal/Saale (m³/s)  available: 2025-06-12T10:00:00Z/2026-06-13T09:45:00Z

  fetched 1000 / 19449
  fetched 2000 / 19449
  fetched 3000 / 19449
  fetched 4000 / 19449
  fetched 5000 / 19449
  fetched 6000 / 19449
  fetched 7000 / 19449
  fetched 8000 / 19449
  fetched 9000 / 19449
  fetched 10000 / 19449
  fetched 11000 / 19449
  fetched 12000 / 19449
  fetched 13000 / 19449
  fetched 14000 / 19449
  fetched 15000 / 19449
  fetched 16000 / 19449
  fetched 17000 / 19449
  fetched 18000 / 19449
  fetched 19000 / 19449
  fetched 19449 / 19449

Saved 19449 rows to '../data/raw/water_data/Q_Blankenstein-Rosenthal_15min.csv'
Station=Saalfeld-Remschütz  Parameter=Q  Freq=15min  2025-01-01T00:00:00Z → 2026-01-01T00:00:00Z

Datastream: [7540] Q@Saalfeld-Remschütz/Saale (m³/s)  available: 2025-06-12T10:00:00Z/2026-06-13T09:45:00Z

  fetched 1000 / 19449
  fetched 2000 / 19449
  fetched 3000 / 19449
  fetched 4000 / 19449
  fetched 5000 / 19449
  fetched 6000 / 19449
  fetched 7000 / 19449
  fetched 8000 / 19449
  fetched 9000 / 19449
  fetched 10000 / 19449
  fetched 11000 / 19449
  fetched 12000 / 19449
  fetched 13000 / 19449
  fetched 14000 / 19449
  fetched 15000 / 19449
  fetched 16000 / 19449
  fetched 17000 / 19449
  fetched 18000 / 19449
  fetched 19000 / 19449
  fetched 19449 / 19449

Saved 19449 rows to '../data/raw/water_data/Q_Saalfeld-Remschütz_15min.csv'
Station=Harra-Lemnitzhammer  Parameter=Q  Freq=15min  2025-01-01T00:00:00Z → 2026-01-01T00:00:00Z

Datastream: [7465] Q@Harra-Lemnitzhammer/Lemnitz (m³/s)  available: 2025-06-12T10:00:00Z/2026-06-13T00:00:00Z

  fetched 1000 / 19449
  fetched 2000 / 19449
  fetched 3000 / 19449
  fetched 4000 / 19449
  fetched 5000 / 19449
  fetched 6000 / 19449
  fetched 7000 / 19449
  fetched 8000 / 19449
  fetched 9000 / 19449
  fetched 10000 / 19449
  fetched 11000 / 19449
  fetched 12000 / 19449
  fetched 13000 / 19449
  fetched 14000 / 19449
  fetched 15000 / 19449
  fetched 16000 / 19449
  fetched 17000 / 19449
  fetched 18000 / 19449
  fetched 19000 / 19449
  fetched 19449 / 19449

Saved 19449 rows to '../data/raw/water_data/Q_Harra-Lemnitzhammer_15min.csv'
Station=Möschlitz  Parameter=Q  Freq=15min  2025-01-01T00:00:00Z → 2026-01-01T00:00:00Z

Datastream: [7494] Q@Möschlitz/Wisenta (m³/s)  available: 2025-06-12T10:00:00Z/2026-06-13T09:45:00Z

  fetched 1000 / 19449
  fetched 2000 / 19449
  fetched 3000 / 19449
  fetched 4000 / 19449
  fetched 5000 / 19449
  fetched 6000 / 19449
  fetched 7000 / 19449
  fetched 8000 / 19449
  fetched 9000 / 19449
  fetched 10000 / 19449
  fetched 11000 / 19449
  fetched 12000 / 19449
  fetched 13000 / 19449
  fetched 14000 / 19449
  fetched 15000 / 19449
  fetched 16000 / 19449
  fetched 17000 / 19449
  fetched 18000 / 19449
  fetched 19000 / 19449
  fetched 19449 / 19449

Saved 19449 rows to '../data/raw/water_data/Q_Möschlitz_15min.csv'
Station=Leutenberg (alt)  Parameter=Q  Freq=15min  2025-01-01T00:00:00Z → 2026-01-01T00:00:00Z

Error fetching No datastream for parameter='Q', freq='15min' on Thing 214. Run explore_api.py → list_datastreams(214) to see what is available.
Station=Katzhütte-Schwarza  Parameter=Q  Freq=15min  2025-01-01T00:00:00Z → 2026-01-01T00:00:00Z

Datastream: [7562] Q@Katzhütte-Schwarza/Schwarza (m³/s)  available: 2025-06-12T10:00:00Z/2026-06-13T09:45:00Z

  fetched 1000 / 19449
  fetched 2000 / 19449
  fetched 3000 / 19449
  fetched 4000 / 19449
  fetched 5000 / 19449
  fetched 6000 / 19449
  fetched 7000 / 19449
  fetched 8000 / 19449
  fetched 9000 / 19449
  fetched 10000 / 19449
  fetched 11000 / 19449
  fetched 12000 / 19449
  fetched 13000 / 19449
  fetched 14000 / 19449
  fetched 15000 / 19449
  fetched 16000 / 19449
  fetched 17000 / 19449
  fetched 18000 / 19449
  fetched 19000 / 19449
  fetched 19449 / 19449

Saved 19449 rows to '../data/raw/water_data/Q_Katzhütte-Schwarza_15min.csv'
Station=Zöllnitz  Parameter=Q  Freq=15min  2025-01-01T00:00:00Z → 2026-01-01T00:00:00Z

Datastream: [7563] Q@Zöllnitz/Roda (m³/s)  available: 2025-06-12T10:00:00Z/2026-06-13T09:30:00Z

  fetched 1000 / 19449
  fetched 2000 / 19449
  fetched 3000 / 19449
  fetched 4000 / 19449
  fetched 5000 / 19449
  fetched 6000 / 19449
  fetched 7000 / 19449
  fetched 8000 / 19449
  fetched 9000 / 19449
  fetched 10000 / 19449
  fetched 11000 / 19449
  fetched 12000 / 19449
  fetched 13000 / 19449
  fetched 14000 / 19449
  fetched 15000 / 19449
  fetched 16000 / 19449
  fetched 17000 / 19449
  fetched 18000 / 19449
  fetched 19000 / 19449
  fetched 19449 / 19449

Saved 19449 rows to '../data/raw/water_data/Q_Zöllnitz_15min.csv'
Station=Mellingen  Parameter=Q  Freq=15min  2025-01-01T00:00:00Z → 2026-01-01T00:00:00Z

Datastream: [7464] Q@Mellingen/Ilm (m³/s)  available: 2025-06-12T10:00:00Z/2026-06-13T09:45:00Z

  fetched 1000 / 19449
  fetched 2000 / 19449
  fetched 3000 / 19449
  fetched 4000 / 19449
  fetched 5000 / 19449
  fetched 6000 / 19449
  fetched 7000 / 19449
  fetched 8000 / 19449
  fetched 9000 / 19449
  fetched 10000 / 19449
  fetched 11000 / 19449
  fetched 12000 / 19449
  fetched 13000 / 19449
  fetched 14000 / 19449
  fetched 15000 / 19449
  fetched 16000 / 19449
  fetched 17000 / 19449
  fetched 18000 / 19449
  fetched 19000 / 19449
  fetched 19449 / 19449

Saved 19449 rows to '../data/raw/water_data/Q_Mellingen_15min.csv'
Station=HRB Straußfurt (AP)  Parameter=Q  Freq=15min  2025-01-01T00:00:00Z → 2026-01-01T00:00:00Z

Datastream: [7486] Q@HRB Straußfurt (AP)/Unstrut (m³/s)  available: 2025-06-12T10:00:00Z/2026-06-13T09:45:00Z

  fetched 1000 / 19449
  fetched 2000 / 19449
  fetched 3000 / 19449
  fetched 4000 / 19449
  fetched 5000 / 19449
  fetched 6000 / 19449
  fetched 7000 / 19449
  fetched 8000 / 19449
  fetched 9000 / 19449
  fetched 10000 / 19449
  fetched 11000 / 19449
  fetched 12000 / 19449
  fetched 13000 / 19449
  fetched 14000 / 19449
  fetched 15000 / 19449
  fetched 16000 / 19449
  fetched 17000 / 19449
  fetched 18000 / 19449
  fetched 19000 / 19449
  fetched 19449 / 19449

Saved 19449 rows to '../data/raw/water_data/Q_HRB_Straußfurt_(AP)_15min.csv'
Station=Artern  Parameter=Q  Freq=15min  2025-01-01T00:00:00Z → 2026-01-01T00:00:00Z

Datastream: [7488] Q@Artern/Unstrut (m³/s)  available: 2025-06-12T10:00:00Z/2026-06-13T09:45:00Z

  fetched 1000 / 19449
  fetched 2000 / 19449
  fetched 3000 / 19449
  fetched 4000 / 19449
  fetched 5000 / 19449
  fetched 6000 / 19449
  fetched 7000 / 19449
  fetched 8000 / 19449
  fetched 9000 / 19449
  fetched 10000 / 19449
  fetched 11000 / 19449
  fetched 12000 / 19449
  fetched 13000 / 19449
  fetched 14000 / 19449
  fetched 15000 / 19449
  fetched 16000 / 19449
  fetched 17000 / 19449
  fetched 18000 / 19449
  fetched 19000 / 19449
  fetched 19449 / 19449

Saved 19449 rows to '../data/raw/water_data/Q_Artern_15min.csv'
Station=Körner  Parameter=Q  Freq=15min  2025-01-01T00:00:00Z → 2026-01-01T00:00:00Z

Datastream: [7587] Q@Körner/Notter (m³/s)  available: 2025-06-12T10:00:00Z/2026-06-13T09:45:00Z

  fetched 1000 / 19403
  fetched 2000 / 19403
  fetched 3000 / 19403
  fetched 4000 / 19403
  fetched 5000 / 19403
  fetched 6000 / 19403
  fetched 7000 / 19403
  fetched 8000 / 19403
  fetched 9000 / 19403
  fetched 10000 / 19403
  fetched 11000 / 19403
  fetched 12000 / 19403
  fetched 13000 / 19403
  fetched 14000 / 19403
  fetched 15000 / 19403
  fetched 16000 / 19403
  fetched 17000 / 19403
  fetched 18000 / 19403
  fetched 19000 / 19403
  fetched 19403 / 19403

Saved 19403 rows to '../data/raw/water_data/Q_Körner_15min.csv'
Station=Werningshausen 2  Parameter=Q  Freq=15min  2025-01-01T00:00:00Z → 2026-01-01T00:00:00Z

Datastream: [7525] Q@Werningshausen 2/Neue Gramme (m³/s)  available: 2025-06-12T10:00:00Z/2026-06-13T09:00:00Z

  fetched 1000 / 19449
  fetched 2000 / 19449
  fetched 3000 / 19449
  fetched 4000 / 19449
  fetched 5000 / 19449
  fetched 6000 / 19449
  fetched 7000 / 19449
  fetched 8000 / 19449
  fetched 9000 / 19449
  fetched 10000 / 19449
  fetched 11000 / 19449
  fetched 12000 / 19449
  fetched 13000 / 19449
  fetched 14000 / 19449
  fetched 15000 / 19449
  fetched 16000 / 19449
  fetched 17000 / 19449
  fetched 18000 / 19449
  fetched 19000 / 19449
  fetched 19449 / 19449

Saved 19449 rows to '../data/raw/water_data/Q_Werningshausen_2_15min.csv'
Station=Erfurt 2 (alt)  Parameter=Q  Freq=15min  2025-01-01T00:00:00Z → 2026-01-01T00:00:00Z

Datastream: [7532] Q@Erfurt 2 (alt)/Schmale Gera (m³/s)  available: unknown

  fetched 0 / 0
Station=Frohndorf 1  Parameter=Q  Freq=15min  2025-01-01T00:00:00Z → 2026-01-01T00:00:00Z

Datastream: [7570] Q@Frohndorf 1/Lossa (m³/s)  available: 2025-06-12T10:00:00Z/2026-06-13T00:00:00Z

  fetched 1000 / 19401
  fetched 2000 / 19401
  fetched 3000 / 19401
  fetched 4000 / 19401
  fetched 5000 / 19401
  fetched 6000 / 19401
  fetched 7000 / 19401
  fetched 8000 / 19401
  fetched 9000 / 19401
  fetched 10000 / 19401
  fetched 11000 / 19401
  fetched 12000 / 19401
  fetched 13000 / 19401
  fetched 14000 / 19401
  fetched 15000 / 19401
  fetched 16000 / 19401
  fetched 17000 / 19401
  fetched 18000 / 19401
  fetched 19000 / 19401
  fetched 19401 / 19401

Saved 19401 rows to '../data/raw/water_data/Q_Frohndorf_1_15min.csv'
Station=Vogelsberg (alt)  Parameter=Q  Freq=15min  2025-01-01T00:00:00Z → 2026-01-01T00:00:00Z

Error fetching No datastream for parameter='Q', freq='15min' on Thing 245. Run explore_api.py → list_datastreams(245) to see what is available.
Station=Frohndorf 2  Parameter=Q  Freq=15min  2025-01-01T00:00:00Z → 2026-01-01T00:00:00Z

Datastream: [7575] Q@Frohndorf 2/Scherkonde (m³/s)  available: 2025-06-12T10:00:00Z/2026-06-13T00:00:00Z

  fetched 1000 / 18903
  fetched 2000 / 18903
  fetched 3000 / 18903
  fetched 4000 / 18903
  fetched 5000 / 18903
  fetched 6000 / 18903
  fetched 7000 / 18903
  fetched 8000 / 18903
  fetched 9000 / 18903
  fetched 10000 / 18903
  fetched 11000 / 18903
  fetched 12000 / 18903
  fetched 13000 / 18903
  fetched 14000 / 18903
  fetched 15000 / 18903
  fetched 16000 / 18903
  fetched 17000 / 18903
  fetched 18000 / 18903
  fetched 18903 / 18903

Saved 18903 rows to '../data/raw/water_data/Q_Frohndorf_2_15min.csv'

In [34]:
print(f"Number of missing stations: {missing_stations}")

n_files = sum(
    1 for f in os.listdir("../data/raw/water_data")
    if os.path.isfile(os.path.join("../data/raw/water_data", f))
)

print(f"Number of successfull files: {n_files}")

Number of missing stations: 32
Number of successfull files: 138

### Exploring Market Price and reBAP Data

In [ ]:
market_price = pd.read_csv("../data/raw/Zeitreihen_Marktpreis_20180930_20260613_UTC.csv", sep=";")
rebap = pd.read_csv("../data/raw/reBAP unterdeckt [2026-06-13 09-51-13].csv", sep=";")
display(market_price.head())
display(rebap.head())

In [ ]:
print("Market Price Info:")
market_price.info()
print("\nReBAP Info:")
rebap.info()

In [ ]:
print("WKA Info:")
wka.info()
print("\nWeather Info:")
weather.info()